### ISSUE TITLE
Issue initializing MotifSimulation

### ISSUE THREAD

**Issue by yvadalia** [winedarksea/AutoTS#105]
probabilities do not sum to 1 for np.random.choice on the following line - 

https://github.com/winedarksea/AutoTS/blob/be79c189d126021309ce6a0e6e8828818e955cb6/autots/models/basics.py#L1023

**Comment by winedarksea** [comment]
Good catch,
that said, this is an experimental model, the "MultivariateMotif" "UnivariateMotif" and "SectionalMotif" are the more mature versions of the same

**Comment by winedarksea** [comment]
Closed by #106
