### ISSUE TITLE
zero forecast generated using statsmodel

### ISSUE THREAD

**Issue by yvadalia** [winedarksea/AutoTS#107]
Looks like all the statsmodels model where `warnings.simplefilter("ignore", category='ConvergenceWarning')` is used are failing and generating zero forecasts

**Comment by yvadalia** [comment]
After looking into simplefilter implementation, it looks like, it is expecting `'category'` as  a class that the warning must be a subclass of.

one way to resolve this - 

```
from sklearn.exceptions import ConvergenceWarning
with warnings.catch_warnings():
    warnings.simplefilter("ignore", category=ConvergenceWarning)
```

**Comment by winedarksea** [comment]
I don't think the warning is the issue, as ETS works just fine.
But I was able to reproduce the issue with ARIMA, generating all zeroes. I will look at that more.

**Comment by winedarksea** [comment]
Out of curiosity, how were you running your code?
It seems like the results are different when being run as main

**Comment by winedarksea** [comment]
I am not sure what exactly the problem was, but I have revamped the warnings in the release today of 0.3.12.
Also as a positive, the silencing is now controlled by the `verbose` argument - warnings will still be printed when `>= 2`

Let me know if problem persists!
