### ISSUE TITLE
Add a parameter to hide all console messages from AutoTS::fit() method.

### ISSUE THREAD

**Issue by dhatwalia** [winedarksea/AutoTS#115]
When we call the fit() method of the AutoTS class, the console is filled with messages which most users do not need to read. It is advisable to have a straightforward way to disable these messages. 

Ideally, providing a boolean parameter called verbose/silent to hide these messages should solve the problem. I would recommend defaulting it to False.

There are three ways to do this:
1. Create a new variable called silent.
2. Rename the currently used verbose variable to something else and create a new boolean variable named verbose.
3. Modify the existing verbose variable to do what we want.

**Comment by winedarksea** [comment]
Currently verbose takes an integer, this is in accordance with the downstream packages some of which use True/False and some use an integer.
```
AutoTS(verbose=0).fit(df)
```
You can also try passing `-1` as an option.

It should do exactly what you are asking for already.

**Comment by dhatwalia** [comment]
Thank you. This works beautifully. Although, I would still recommend defaulting verbose to 0.
