### ISSUE TITLE
Add accessibility to subdivision keyword (states, ...) from the holidays package?

### ISSUE THREAD

**Issue by El-Don-Quijote** [winedarksea/AutoTS#132]
Hi,

**Is your feature request related to a problem? Please describe.**
It would be very nice to also have accessibility to the holidays package "subdiv" keyword, which allows to specify a country's subdivision. It can be the case, that different states have different holidays, which can influence some time series. 

**Describe the solution you'd like**
Allow for a "holiday_subdiv" list in "create_regressor", which should not be much effort, as the functionality is offered by an already used package. 

**Additional context**
This is my first time commenting on an issue or adding a feature request. I very much appreciate your work!

Looking forward hearing from you!

**Comment by winedarksea** [comment]
Latest release #133 allows passing a dictionary with country: subdivision. This does have the limitation of only allowing one subdivision to be specified. Also related new features: holiday detector (auto detected holidays) option and binary encoded holidays instead of simple flag.
```python
regr_train, regr_fcst = create_regressor(
    df,
    forecast_length=forecast_length,
    frequency=frequency,
    drop_most_recent=drop_most_recent,
    scale=True,
    summarize="auto",
    backfill="bfill",
    fill_na="spline",
    holiday_countries={"US": "PR"},  # requires holidays package
    encode_holiday_type=True,
    # datepart_method="simple_2",
)
```

**Comment by El-Don-Quijote** [comment]
Great work, thank you!
