### ISSUE TITLE
self.best_model_name = self.best_model['Model'].iloc[0]

### ISSUE THREAD

**Issue by meetu30** [winedarksea/AutoTS#140]
Hi,
I am facing difficulty running the model. I have selected some models in a list - best_model. There are 3 of them, and technically model.fit should run all those 3, and give result based on the best one. Sometimes it works, sometimes it throws error with this iloc[0] position statement. It seems it is not able to read the list because I already have 3 algo names there, then how is it not able to read 0th element. Initially i was passing just 1 name, i got same error, then i added 2, now there are 3 algo names, still the same error popping up randomly. What is the root cause of this issue and how can i fix it?  Kindly guide.

**Comment by winedarksea** [comment]
Some code would help me understand the issue, but what I think is happening is you are passing a model to `AutoTS().best_model`. That will only allow ONE model to be passed. Now, that model can be of type `Ensemble` which would allow you to run 3 models, but manually defining a Ensemble might be a little tricky.
You have some other options that might work better. `import_template` will import a template, which is just a csv or json file of model definitions. Probably the simplest thing would be to use the `model_forecast` function and run each model separately.

**Comment by meetu30** [comment]
So, instead of running "fast-parallel" class of algos (which will take a lot of time), I am giving a list of algos like this -
best_model=['SectionalMotif']
but with just 1 model, it worked fine initially. but after sometime, I got this iloc[0] error. So I added another 2-
best_model=['SectionalMotif','UnivariateMotif','GLM']
Again, it worked well for sometime, but then I encountered the same error. 

I am running the below code -
model = AutoTS(
                forecast_length = 180,        # number of periods to forecast ahead
                frequency = 'D',
                prediction_interval = 0.9,
                ensemble = ensemble,
                max_generations = 8,
                num_validations = 2,
                no_negatives = True,         # forces forecasts to be greater than or equal to 0
                model_list = best_model,
                #model_list="fast_parallel",    # provide your OWN CUSTOM model list
                constraint = 2.0,
                n_jobs = 'auto', ## or set to number of CPU cores
                metric_weighting = metric_weighting,
                )  
What I am not able to understand  is, giving the algorithm this way, should not create an issue...and it doesnot create any, as expected, but then after few runs, why it is not able to find that best_model[0] element, when its already there? Kindly guide.

**Comment by winedarksea** [comment]
So, some confusion is because AutoTS already has an attribute `best_model` which is completely unrelated to `model_list`. You just happened to chose a variable name that I also use somewhere else.
You can see that in the code here:
https://github.com/winedarksea/AutoTS/blob/master/autots/evaluator/auto_ts.py#L1593

Your `model_list=['SectionalMotif']` arg as written is completely fine. There is some other error occurring during your model run. Could you post the full error message? Also make sure you are updated to the latest version of AutoTS.

**Comment by meetu30** [comment]
oh ok, I will change the variable name. Kindly see  the error. 
model = model.fit(df, date_col='wk_start', value_col='sales')
self.best_model_name = self.best_model['Model'].iloc[0]
<html>
<body>


File "/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py", line 2138, in _getitem_axis | File "/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py", line 2138, in _getitem_axis
ile "/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py", line 2063, in _validate_integer
raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds


Couple of things -
1. I am running this on AWS Batch. Surprisingly, all this code works perfectly fine on AWS EC2 instance, but on batch creates trouble. And i did check the logs, algorithms just stop working randomly. For example, MultivariateMotif sometimes worked, sometimes not. (on EC2 it always worked though). So I had to remove it from the list. 
2. Next, after skipping MultivariateMotif, i passed another algo, and this is when i got the error. Kindly check. TIA
3.

**Comment by winedarksea** [comment]
Unfortunately, I can't tell much from that error. It seems to be missing the model, for some reason?

As for AWS Batch, my guess would be a lack of RAM or other resources, or even more likely, a multiprocessing conflict (try setting n_jobs=1 and see if it crashes). Random crashes that don't seem to occur to any software bug are usually a lack of resources

you left a blank 3. there, was there more?

**Comment by meetu30** [comment]
I am sure that its not related to RAM and CPU issues because its on AWS cloud platform(batch). I tried changing the variable to "bestModel" (earlier it was best_model) and also set the n_jobs to 1. But again the same thing happened. As a solution, appending 2-3 more models to list solves the issue temporarily, but it does randomly surface up.
Sorry, nothing is there in point 3, typo.

**Comment by winedarksea** [comment]
Best I can say is let me know if you find out any more, as I haven't been able to reproduce the issue myself.
