### ISSUE TITLE
fbprophet is replaced by prophet in new version.

### ISSUE THREAD

**Issue by oleotiger** [winedarksea/AutoTS#152]
In `auto_ts/models/build_prophet.py` , `from fbprophet import Prophet # type: ignore` reports error: ModuleNotFoundError: No module named 'fbprophet'. 

According to `https://facebook.github.io/prophet/docs/installation.html`,
```
From v0.6 onwards, Python 2 is no longer supported.
As of v1.0, the package name on PyPI is “prophet”; prior to v1.0 it was “fbprophet”.
As of v1.1, the minimum supported Python version is 3.7.
```
What version of auto-ts is compatible with fbprophet v1.0 or v1.1?

**Comment by winedarksea** [comment]
Have you made sure prophet is installed into your environment? It is not install as a dependency so you will need to run `pip install prophet` or `conda install prophet`
I am currently using prophet==1.1.1 and it works fine
AutoTS has had for several years a try/except block where it tries to load `prophet` and if that fails then tries to load `fbprophet`.
