### ISSUE TITLE
 Exception: Transformer Detrend failed on fit

### ISSUE THREAD

**Issue by r-matsuzaka** [winedarksea/AutoTS#159]
Hello.  
Could you tell me what the message would indicate?

>    3610         # df = df.replace([np.inf, -np.inf], 0)  # .fillna(0)
>    3611 except Exception as e:
> -> 3612     raise Exception(
>    3613         f"Transformer {self.transformations[i]} failed on fit"
>    3614     ) from e
>    3615 # df = df.replace([np.inf, -np.inf], 0)  # .fillna(0)
>    3616 return df
> 
> Exception: Transformer Detrend failed on fit

**Comment by winedarksea** [comment]
It means the Transformer failed, but more is hard to say. You can set verbose=2 or higher to get more traceback details. Normally this means that the model itself is returning an NaN or similar value. You can try experimenting with removing or changing parameters in model_forecast. 
You could also share the actual model parameters and data and I can look at it.

**Comment by r-matsuzaka** [comment]
Thank you for the prompt reply.  
I will see the logs with `verbose=2`.

**Comment by r-matsuzaka** [comment]
I got another error.  
Here is my setting.

```
    model = AutoTS(
        forecast_length=8,
        frequency='MS',
        prediction_interval=0.9,
        ensemble=None,
        model_list="superfast",  # "superfast", "default", "fast_parallel"
        transformer_list="superfast",  # "superfast",
        drop_most_recent=0,
        max_generations=1,
        num_validations=1,
        validation_method="backwards",
        verbose=2
    )
```

>    3610         # df = df.replace([np.inf, -np.inf], 0)  # .fillna(0)
>    3611 except Exception as e:
> -> 3612     raise Exception(
>    3613         f"Transformer {self.transformations[i]} failed on fit"
>    3614     ) from e
>    3615 # df = df.replace([np.inf, -np.inf], 0)  # .fillna(0)
>    3616 return df
> 
> Exception: Transformer PowerTransformer failed on fit
> CPU times: user 1h 8min 5s, sys: 6.6 s, total: 1h 8min 1

**Comment by winedarksea** [comment]
Must be a very large dataset if one "superfast" generation takes an hour.
Could you also post the:
`model.best_model_params` which is the chosen model causing issues

**Comment by r-matsuzaka** [comment]
Thank you for the response.  
> Must be a very large dataset if one "superfast" generation takes an hour.
I want to do try and error quickly. So I choose it.

> model.best_model_params which is the chosen model causing issues
I did not log this info.
I will try again.

**Comment by r-matsuzaka** [comment]
By the way, what is the max number for `verbose` I can choose?

https://github.com/winedarksea/AutoTS/blob/52487e5ea5e3ce0530e1096e239655786227de3f/autots/evaluator/auto_ts.py#L122

**Comment by winedarksea** [comment]
There isn't really a max for verbose,  I try to set it to allow any number. But generally above 3 it doesn't do anything.
It does get passed through to some underlying models (like sklearn for those) where the verbosity will have different effects.
For practical purposes: -1 = no messages (hopefully), 0 = only critical errors 1 = informational messages and >= 2 is debug messages

**Comment by r-matsuzaka** [comment]
I understood. Thank you very much. Then I use 3.

**Comment by r-matsuzaka** [comment]
I may solve the issue after using frequency='M'.  
I use monthly data.  
At first and second trial, I used `infer` and `MS` then I got the above errors.

**Comment by r-matsuzaka** [comment]
No, I get the first error again.


```
    model = AutoTS(
        forecast_length=8,
        frequency='M',
        prediction_interval=0.9,
        ensemble=None,
        model_list="superfast",  # "superfast", "default", "fast_parallel"
        transformer_list="superfast",  # "superfast",
        drop_most_recent=0,
        max_generations=2,
        num_validations=1,
        validation_method="backwards",
        verbose=3
    )
```


>    3610         # df = df.replace([np.inf, -np.inf], 0)  # .fillna(0)
>    3611 except Exception as e:
> -> 3612     raise Exception(
>    3613         f"Transformer {self.transformations[i]} failed on fit"
>    3614     ) from e
>    3615 # df = df.replace([np.inf, -np.inf], 0)  # .fillna(0)
>    3616 return df
> 
> Exception: Transformer Detrend failed on fit

**Comment by r-matsuzaka** [comment]
Model info:  

```
Initiated AutoTS object with best model: 
LastValueNaive
{'fillna': 'rolling_mean', 'transformations': {'0': 'Detrend'}, 'transformation_params': {'0': {'model': 'Linear', 'phi': 1, 'window': None, 'transform_dict': {'fillna': None, 'transformations': {'0': 'AnomalyRemoval'}, 'transformation_params': {'0': {'method': 'zscore', 'transform_dict': {'transformations': {'0': 'DatepartRegression'}, 'transformation_params': {'0': {'datepart_method': 'simple_3', 'regression_model': {'model': 'ElasticNet', 'model_params': {}}}}}, 'method_params': {'distribution': 'uniform', 'alpha': 0.05}}}}}}}
{}
SMAPE: 1.4285051944410174, 0.8321593634596656
MAE: 0.03615071044941742, 0.020486762593758256
SPL: 1.063648479208527, 0.6940963883965834
```


Also `model.best_model_params` is empty.

**Comment by r-matsuzaka** [comment]
I do not know the reason but after increasing generation number, solved.  
But chosen model was still the same...
