### ISSUE TITLE
Does it support categorical data ?

### ISSUE THREAD

**Issue by Pranjal-bisht** [winedarksea/AutoTS#173]
Does this model support Time series model for categorical data along with date and value parameters ?

**Comment by winedarksea** [comment]
Your 'value' can be categorical. It accepts a multivariate input so you can pass it there alongside any numeric targets.
You might also be talking about the `future_regressor` which only accepts numeric inputs, but you could easily use pd.get_dummies to convert a categorical feature to numeric for the regressor input.
