### ISSUE TITLE
Multivariate Models

### ISSUE THREAD

**Issue by carterrees-entrata** [winedarksea/AutoTS#175]
I understand that multiple time series can be modeled. However, does that mean each time series can have its own unique solution? For example, if I fed autots 10 series, does it find the best model for each of the series, potentially returning 10 different models with unique parameters?

**Comment by winedarksea** [comment]
Yes, it will return 10 time series if you input 10 time series. Some models can handle 10 at once, but if you want 10 unique models you can use the `ensemble=['horizontal-max']` which will find the optimal model per time series.
Look at the example datasets, all are multiple time series (I usually use the word 'multivariate' time series to refer to this case).

**Comment by carterrees-entrata** [comment]
Excellent, thank you for the quick response. Looking forward to seeing what AutoTS can do for my projects.

**Comment by carterrees-entrata** [comment]
Following up here. I was able to run the ensemble = 'horizontal-max' on the wiki data set. How do I go about matching the algorithm used to model each specific series? My set up is as follows: 

`model = AutoTS(
    forecast_length=21,
    frequency='infer',
    prediction_interval=0.9,
    ensemble='horizontal-max',
    model_list="superfast",  # "superfast", "default", "fast_parallel"
    transformer_list="superfast",  # "superfast",
    drop_most_recent=1,
    max_generations=4,
    num_validations=2,
    validation_method="backwards"
)`

When I run print(model) I can see that the ensemble model count is 12. There are 21 series represented in the data. Given the previous discussion in this thread, I am assuming that some of the series share the same optimized model.

**Comment by carterrees-entrata** [comment]
I may have found the answer to my own question if you can confirm.

I see this model from the print(model) statement: `'d0024dfa35ff455302e3534a9de6af8e': {'Model': 'LastValueNaive', 'ModelParameters': '{}', 'TransformationParameters': '{"fillna": "ffill", "transformations": {"0": "AlignLastValue", "1": "SeasonalDifference", "2": "RobustScaler", "3": "MinMaxScaler"}, "transformation_params": {"0": {"rows": 1, "lag": 2, "method": "additive", "strength": 0.5, "first_value_only": false}, "1": {"lag_1": 7, "method": "Median"}, "2": {}, "3": {}}}'`

Further down in that statement I see the following series name that share the same key. I assume that they all share the same modeling solution.

- 'wiki_Google_Chrome': 'd0024dfa35ff455302e3534a9de6af8e'
- 'wiki_Christmas': 'd0024dfa35ff455302e3534a9de6af8e'
- 'wiki_William_Shakespeare': 'd0024dfa35ff455302e3534a9de6af8e'

-

**Comment by winedarksea** [comment]
Yes, you are correct.
Generally the more models you have in your list (try `fast` over `superfast`) and the more generations you run (I would recommend >50 or so if you have the time and compute), the more choices there will be, and the fewer repeat models are used. Although repeat models isn't necessarily a bad thing, as it can be more efficient to compute, in fact if you just specify `ensemble='horizontal'` it will automatically try to choose a smaller number of models. Horizontal-max assures using as many models as possible for highest possible accuracy.

**Comment by carterrees-entrata** [comment]
Got it. Thank you. I've got the compute power and plan on trying some of the gpu functionality.
