### ISSUE TITLE
Export final models to csv along with unique keys

### ISSUE THREAD

**Issue by carterrees-entrata** [winedarksea/AutoTS#177]
I have successfully run AutoTS on a wide data set with 195 series. Successfully saved validation results `validation_results = model.results("validation"),` model results `model_results = model.results()` and the forecasts `forecasts_df = prediction.forecast.` 

However, I'd like to save the the output which includes the models actually used (47 in this case) and be able to connect them to their corresponding series via the unique key. This would allow me to document what the final tuned model was that produced the forecast for each series.

When I call `model = model.fit(processed_dataframe)` and then `print(model)` I can see all the relevant info I want but it is still packed inside the AutoTS object. Is there a way to pull this particular data in to a csv file or a text file?

**Comment by winedarksea** [comment]
You are looking for the `export_template` command. It can pass to a csv or json file name, the best models. It has a matching `import_template` for loading them in when a model starts.
