### ISSUE TITLE
Save best model for each serie instead of best model overall

### ISSUE THREAD

**Issue by YahyaL** [winedarksea/AutoTS#203]
Just discovered this library and it's functionnalities. I read past issues related to exporting the best model. My understanding is that we are NOT exporting the template for the best model for each time-serie but the best performing model overall for all time-series (when n=1). This means that during deployment, the best model overall will generate the forecasts for all series, which may degrade the performance for individual series where we are using a suboptimal model.
Would it be better in a use case where we have to generate daily forecasts for thousands of time-series to save the best model for each time-serie and retrain only the best model daily with new data? I can for example find the best model for each serie once a month and then use that same model for that serie for the whole month.
Is this approach accurate?
Thanks!

**Comment by winedarksea** [comment]
What you want is `ensemble=['horizontal-max']`
which is where it chooses the best model per series, exactly as you are asking for. It packages that all up in a single Ensemble model parameter set (usually a pretty massive piece of json). 
To graph the chosen models by type:
```python
if model.best_model_ensemble == 2:
    plt.subplots_adjust(bottom=0.5)
    model.plot_horizontal_transformers()
    plt.show()
    model.plot_horizontal_model_count()
    plt.show()
```

**Comment by YahyaL** [comment]
Tried it and it's exactly what I was looking for. Thanks!
