### ISSUE TITLE
adding autos package to https://repo.anaconda.com/pkgs/snowflake/

### ISSUE THREAD

**Issue by shuaiwang88** [winedarksea/AutoTS#211]
I'd like to add the autots package into https://repo.anaconda.com/pkgs/snowflake/, so it will work with snowpark.

**Comment by winedarksea** [comment]
https://community.snowflake.com/s/article/how-to-use-other-python-packages-in-snowpark

It says near the bottom that the only way to add models to their repo is to submit a request to Ideas on their site

**Comment by shuaiwang88** [comment]
Just submitted. Thanks!
