### ISSUE TITLE
Predict time intervals

### ISSUE THREAD

**Issue by Gpen997** [winedarksea/AutoTS#49]
How to predict time intervals in auto_ts in python

**Comment by winedarksea** [comment]
https://github.com/winedarksea/AutoTS/blob/master/extended_tutorial.md

If you could be more specific, that would be helpful

**Comment by Gpen997** [comment]
I want to predict confidence intervals for data 0.95 and 0.90 
How to split data for test and train in autots

**Comment by winedarksea** [comment]
If you read the documentation and the docstrings you will see answers to this...
For prediction interval, pass `prediction_interval=0.95` (or whatever you desire) to the AutoTS() init. Then access the results:
```
prediction = model.predict()
upper_forecasts_df = prediction.upper_forecast
lower_forecasts_df = prediction.lower_forecast
```

and for train/test split, this is also clearly discussed in the documentation.
```
model = AutoTS(... other parameters...
    num_validations=2,
    validation_method='even',
    )
```
Read the extended_tutorial for a discussion of different train/test split options.
