### ISSUE TITLE
Wide Format

### ISSUE THREAD

**Issue by catchlui** [winedarksea/AutoTS#54]
Hello ,

Can i create a multiseries multivariate model using wide format ? this feature is available in the long format , but not there in the wide format ? If there is no such features available then we need to do one by one ?

my data looks like this

store A  - Product A (time series data) Product B (time series Data) so on
Store B - Also has similar pattern .

Also i need to add external regressor. My external  regressor has more than one variable. One idea is to do a dimension reduction and take it ? Or can i provide multi dimension data for external regressor ?

Please help

**Comment by winedarksea** [comment]
If you want to learn how to shape your data, take a look at the examples with `long=False`. I'd rename your columns `storeA_product1, storeA_product2, storeB_product1` and so on, and the just pass as many columns as you need. Behind the scenes all data is made into the "wide" format before AutoTS runs the models.
For regressors try following the example here:
https://github.com/winedarksea/AutoTS/blob/dev/extended_tutorial.md#adding-regressors-and-other-information
Some models only take one variable but I handle the dimensionality reduction for you, so pass in as many variables as you want for a regressor.

**Comment by shuaiwang88** [comment]
@winedarksea  Do I create every autots for each store_product, by using a loop? 
like: 
for p in store_prodct:
   model  = autots(subset, x, x, ,x )

**Comment by winedarksea** [comment]
You can do it that way, however autots expects multivariate data so either passing wide style data or using long format data with the series_id distinct for each store_product.
For large scale it often makes sense to combine the two approaches. Loop AutoTS through high level groupings like product category or store regions, then in each of those subsets run a single AutoTS run on all store_products

**Comment by shuaiwang88** [comment]
I added a column company in the data you mentioned.
![image](https://github.com/winedarksea/AutoTS/assets/14266357/9612c408-fb2d-4e31-ba30-584a5b8ee817)

For the model.fit, I just passed id_col = 'company':
model = model.fit(
    df,
    id_col='company',
)
Is this correct?

**Comment by winedarksea** [comment]
So your data format in that example data is `wide` style data. In this case, each column is a target series. So instead of CSUSHPISA you would have "companyB_product1" and for EMVOVERALLEMV you might have "companyA_product1" or whatever as appropriate
If using `long` style data your approach would work if you had three target series, and company was the series_id

**Comment by shuaiwang88** [comment]
I see. What I am really want to do is using exogenous variables, with series id: adding a company part in the traffic example with different weight [wide format traffic](https://winedarksea.github.io/AutoTS/build/html/source/tutorial.html#id3)
Any suggestions?

**Comment by winedarksea** [comment]
`future_regressor` is for those features which you know about the future. For series you don't know in the future, pass them in as additional series to forecast and some multivariate models will use them as features. I haven't personally found much actual value in a single categorical feature that is constant so there isn't direct support for that all though you could pass it in as a future regressor. Study the production_example.py in this repo for one general approach
