### ISSUE TITLE
Great Work!

### ISSUE THREAD

**Issue by firmai** [winedarksea/AutoTS#6]
Hi man, 

I can't believe I discovered the project just now! I thought I was the only one scratching my head as to why something like this does not exists. You seem to have progressed further than me, I have been busy with it just the last week or so. A few of the things I want to do you already seemed to have done. The following is what I want to work on:

AtsPy Future Development

    1. Additional in-sample validation steps to stop deep learning models from over and underfitting.
    1. Extra performance metrics like MAPE and MAE.
    1. Improved methods to select the window lenght to use in training and calibrating the model.
    1. Add the ability to accept dirty data, and have the ability to clean it up, inetrpolation etc.
    1. Add a function to resample to a larger frequency for big datasets.
    1. Add the ability to algorithmically select a good enough chunk of a large dataset to balance performance and time to train.
    1. More internal model optimisation using AIC, BIC an AICC.
    1. Code annotations for other developers to follow and improve on the work being done.
    1. Force seasonality stability between in and out of sample training models.
    1. Make AtsPy less dependency heavy, currently it draws on tensorflow, pytorch and mxnet.

I am going to take a small break from development for the next month to write a paper, but I look forward to learning from your project and including some tidbits of your work in my own. For what its worth, I am going to make you a collaborator for AtsPy so if you see anything out of the ordinary don't be afraid to tinker.  We might be up to something slightly different, in my project I want to emphasise the "no effort" factor and give users the ability to retrieve the model and access parameters. If our projects converge then maybe we should think about collaboration. 

Regards,
Derek  

edit AtsPy - https://github.com/firmai/atspy

**Comment by winedarksea** [comment]
Great to hear from you!
I see no harm in us developing parallel solutions - like TPOT and autosklearn there'. I'm not working too hard either myself - on vacation down in what I believe is your home country of New Zealand.

**Comment by winedarksea** [comment]
n

**Comment by sophiarora** [comment]
Take a look at the following link. H2O is a  big advocate in this field. And they are recruiting.

http://docs.h2o.ai/driverless-ai/latest-stable/docs/userguide/time-series.html
