### ISSUE TITLE
Why is the best result returned by the model not the best according to the resulting dataframe? 

### ISSUE THREAD

**Issue by wilfreddesert** [winedarksea/AutoTS#68]
Hi, 

```
long = True
# df = load_monthly(long=long)

from autots import AutoTS

metric_weighting = {
    "smape_weighting": 5,
    "mae_weighting": 1,
    "rmse_weighting": 0,
    "containment_weighting": 0,
    "runtime_weighting": 0,
    "spl_weighting": 0,
    "contour_weighting": 0,
}

model = AutoTS(
    forecast_length=30,
    frequency="infer",
    prediction_interval=0.9,
    ensemble=None,
    model_list="superfast",
    transformer_list="fast",
    max_generations=15,
    num_validations=5,
    validation_method="backwards",
    metric_weighting=metric_weighting,
)
model = model.fit(
    df,
    date_col="ds" if long else None,
    value_col="y" if long else None,
    id_col="series" if long else None,
)

prediction = model.predict()

forecasts_df = prediction.forecast
# upper and lower forecasts
forecasts_up, forecasts_low = prediction.upper_forecast, prediction.lower_forecast

# accuracy of all tried model results
model_results = model.results()
validation_results = model.results("validation")
```

After the run, I get the following `Initiated AutoTS object with best model:  AverageValueNaive`, but then if I sort the `validation_results` dataframe by `Score` or `smape`, the first place is taken by another model, not this one. 

Probably, I don't completely understand the way the best model is reported. Thank you in advance!

**Comment by winedarksea** [comment]
@wilfreddesert  
I would check the number of `Runs` which is a column in the results there. If everything is as expected, the highest scoring model with `Runs == 6` in this case will be the chosen model. 
So definitely confusing, sorry, but the validation results still includes those which weren't run through validation, but only run on the initial dataset. Since, basically, overfitting happens and other validation segments can be 'harder' those scores are higher. Compare as well to the model_results table and you should see the chosen model doing even better on that first validation section than what you are seeing in validation_results.

**Comment by wilfreddesert** [comment]
In this case, the number of runs equals 4, is that wrong? Sorry if my questions are too trivial. I have thoroughly read the quickstart guide, but it seems that I haven't yet grasped the logic behind the results returned :) 

So, if I understand correctly, it's always the model with the largest number of runs and the smallest Score which is considered the best, right?

**Comment by winedarksea** [comment]
@wilfreddesert 
Number of runs should equal `num_validations + 1`. One initial testing set, then as specified N validation sets. You've got 5 specified here, so 6 seems like what I would be expecting if you used the code above. 

If you are seeing less than that, its because the model is failing on some of the validations. This most often happens when you have a bunch of early data with a bunch of NaNs in it. Do you have any models with Runs==6 at all here?

And yes, not all of this is thoroughly polished yet. Do you think it would help if validation_results only returned models that had passed successfully through all validations?

**Comment by wilfreddesert** [comment]
@winedarksea , thank you for answering. It seems that a few runs failed and this is why the maximum number of runs is 4 in my case. 
I don't see any obvious reasons for those failures though given that I have no NaNs in my dataframe. I think that the currently returned dataframe is okay if not slightly unintuitive as I wrote above. I spent quite some time trying to understand how the best model was derived from this table. 

Can you please also suggest a way to compare the selected superfast model with a more heavyweight one like Prophet. As far as I understand, it's possible to just switch from the superfast mode and then those fancier models will be used, but what if I want to compare the best superfast model with only one, say, Prophet? 

Currently, the validation metrics reported are a black box in some way and there is no way to do any benchmarking because there is no access to the validation folds. One idea would be to save a holdout part of the dataset, but this is not super desirable since I would rather have all the data included for training. 

Thanks in advance!

**Comment by winedarksea** [comment]
@wilfreddesert 
```python
model_list = [
    'ZeroesNaive',
    'LastValueNaive',
    'AverageValueNaive',
    'GLS',
    'SeasonalNaive',
    'Prophet',
] # make sure Prophet is installed first as it isn't a required dependency
```

The forecasts are not saved because it takes a ton of memory to save the forecasts for hundreds of models if working with larger data, but I'm thinking of adding a parameter that allows the results to be saved in an accessible way...

**Comment by wilfreddesert** [comment]
Thank you. Can you please also help me with the following error:
`Model Number: 79 with model FBProphet in generation 1 of 3
Template Eval Error: ValueError('Unable to coerce to Series, length must be 1: given 1063') in model 79: FBProphet`

It's strange because during the validation process all the models run successfully at least once, but once in a while, the error above occurs for some of them. 

Another question is whether it's correct to just set some column with the same value everywhere as series_id when you have only one series in your dataframe

**Comment by winedarksea** [comment]
@wilfreddesert 
That error is coming either from a bug in either ClipOutliers or Detrend transformer I think, nothing to do with Prophet. It won't effect modeling at all, with so many possible transformation and model parameter combinations, combinations just come up that don't play nicely together, and thus a few errors are expected and not worth worrying about.

You can pass `series_id = None` or you can set the index to be the datetime, and just pass it in with `series_id, date_col,` and `value_col` all `None. You don't need a series_id in the univariate case, although it should be fine if you do as you say.

**Comment by wilfreddesert** [comment]
@winedarksea , thank you, got it. 

Can you please also suggest a convenient way to save the model configuration so that I can use it afterwards like:

```
model = <load_model>
model.fit(new_data)
predictions = model.predict(...)
```

I have seen it's possible to export and import templates, but it seems that the template is loaded after initializing your model with hyperparameters so this is not supposed to be the final model, rather a way to limit the exploration space. 

Probably, it's possible to save the best model config and then load it?

**Comment by winedarksea** [comment]
Saving the raw model is not possible nor generally advisable, the nature of time series is they are constantly changing (at least, most real world ones are)
See here:
https://github.com/winedarksea/AutoTS/blob/master/extended_tutorial.md#deployment-and-template-importexport
just set n=1 if you only the one best model exported. I usually like having multiple as it allows it to choose a slightly different model if things have changed.
