### ISSUE TITLE
cannot import name 'AutoTS'

### ISSUE THREAD

**Issue by Louis24** [winedarksea/AutoTS#81]
Traceback (most recent call last):
  File "C:/Zero/Python/时间序列比较/autots.py", line 8, in <module>
    from autots import AutoTS, load_daily
  File "C:\Zero\Python\时间序列比较\autots.py", line 8, in <module>
    from autots import AutoTS, load_daily
ImportError: cannot import name 'AutoTS'

**Comment by winedarksea** [comment]
@Louis24  This usually means the package is not installed.
Have you run `pip install autots` or `python -m pip install autots` ?
If you will are running source code downloaded from GitHub, you will need to make sure it is in your working directory or on your system Python path.
The extended tutorial has more detailed instructions if needed.

**Comment by Louis24** [comment]
haha thanks, I accidentally named the script as this autots. The call is wrong.
