### ISSUE TITLE
NaN in prediction

### ISSUE THREAD

**Issue by treexterr** [winedarksea/AutoTS#87]
Hi. Thx for great job!

I've got NaN in prediction, while the prediction horizon started one timestamp earlier.

What  I did wrong?

http://joxi.ru/82Q1PXDcVR69B2

**Comment by winedarksea** [comment]
I'm very reluctant to click on that link (I've never seen joxi.ru before), sorry... Maybe there is some other way to provide information?

Best guess is that it is a problem with how your data is being loaded.
Check `model.df_wide_numeric` where `model` is your fit AutoTS object. Does that look correct to you?

If it is an error with modeling, there's usually a simple way to check: simply run AutoTS again. Bugs in models are unlikely to be seen consistently, as different models are usually chosen on a new run.
