### ISSUE TITLE
SinTrend failed with IndexError('index 1 is out of bounds for axis 0 with size 0')

### ISSUE THREAD

**Issue by LukeBeckerBB** [winedarksea/AutoTS#89]
Hello,

for some reason I get an error that I did not get before. 
I am using the same code and same data that worked before, but I still get the error.

Anyone else experiencing this issue? 

Error:
SinTrend failed with IndexError('index 1 is out of bounds for axis 0 with size 0')

Kind regards
Luke

**Comment by winedarksea** [comment]
SinTrend is a somewhat finicky transformer.
If you use `transformer_list="fast"` it won't include SinTrend  (that's SineTrend by a different spelling)

I'll look and see if I can find anything weird with it

**Comment by LukeBeckerBB** [comment]
Thank you very much for the fast answer. 

However, I get the same error when I use transformer_list='fast'

**Comment by winedarksea** [comment]
I'm guessing that's because you're importing a template with SinTrend in it, and transformer_list isn't enforced on imported templates when transformer_list = "fast"...

Is your model actually failing, or is it just an annoying warning message?

**Comment by LukeBeckerBB** [comment]
I am not quite sure what you mean by the template import. 

But, yes unfortunately the model is actually failing and AutoTS won't return a forecast. I will try it with only one time series and different data to double check, whether I am doing something wrong. But for me the same data and same code worked last week.

**Comment by winedarksea** [comment]
So is the only change then that you've updated to 0.3.6 version of AutoTS?

This is what I mean by template import:
https://github.com/winedarksea/AutoTS/blob/master/extended_tutorial.md#deployment-and-template-importexport

**Comment by LukeBeckerBB** [comment]
So also with other database it is not working. 

I am using Version 0.3.5 and I am not using template import. 

So I didnt change anything to the running version a couple days back. Does it currently work for you wothout any issues. If only I am having the issue, then I'll need to check what I can do different.

**Comment by winedarksea** [comment]
I was able to reproduce your error, it takes a very specific combination:
fill_na = "fake_date"
SinTrend transformer used
and one or more series that are entirely NaN

Finding and removing the NaN series would fix the problem, otherwise I'll release a bug fix for this soon in 0.3.7

**Comment by LukeBeckerBB** [comment]
I just used a test dataset with full data (no NaN). Seems to be working also with transformer_list='all'. 

Thank you very much for your support. I really appreciate the great work you are doing!
