### ISSUE TITLE
Very good AutoTs, can you tell me how to save the trained model for reading instead of training every time? 

### ISSUE THREAD

**Issue by fsz168** [winedarksea/AutoTS#90]
Very good AutoTs, can you tell me how to save the trained model for reading instead of training every time?

**Comment by winedarksea** [comment]
See the "Running Just One Model"  and "Template Import/Export" section:
https://github.com/winedarksea/AutoTS/blob/master/extended_tutorial.md#deployment-and-template-importexport

You can find the best model in a df `model.best_model` from your AutoTS run.

It's not quite the same as other machine learning. You could pickle it and reload, but with time series, you always should update the training dataset with the latest data then generate your forecast - generating forecasts with old data leads to bad forecasts.

**Comment by fsz168** [comment]
Thank you very much, you are the best！
